version: 0.2
phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - aws --version
    - aws ecr get-login-password | docker login --username AWS --password-stdin 222512976514.dkr.ecr.ap-northeast-1.amazonaws.com
  build:
    commands:
    - echo Build started on `date`
    - echo Building Java
    - cd claim-service
    - mvn compile
    - mvn package -DskipTests
    - docker --version
    - echo Building the docker image..
    - docker build -t claim-service .
    - echo Checking docker image claim-service
    - docker images --filter reference=claim-service
    - docker tag claim-service 222512976514.dkr.ecr.ap-northeast-1.amazonaws.com/claim_ecr_repository:claim-service
    - echo Checking tag added before the docker image
    - docker images
  post_build:
    commands:
    - echo Build completed on `date`
    - echo Pushing docker image
    - docker push 222512976514.dkr.ecr.ap-northeast-1.amazonaws.com/claim_ecr_repository
    - echo Writting definition file
    - printf '[{"name":"claim-claim-container-935172","imageUri":"%s"}]' 222512976514.dkr.ecr.ap-northeast-1.amazonaws.com/claim_ecr_repository:claim-service > imagedefinitions.json
artifacts:
  files:
  - claim-service/imagedefinitions.json